## Load data and packages

In [1]:
import random
import numpy as np
import scanpy as sc
import anndata as an
import scipy.stats as st
from scipy.spatial import KDTree
import math
from numba import njit
from numba import jit

In [2]:
def LoadData(path):
    adata = sc.read_visium(path)
    adata.var_names_make_unique()
    return adata

In [3]:
path ="/Users/juliafoyer/Documents/Skolarbete/Masters_thesis/human_breast_cancer_ST_data"
adata = LoadData(path)

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.


In [4]:
X = np.array(adata.X.todense())

In [5]:
adata.X = X

In [6]:
X.shape

(3798, 36601)

In [7]:
sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata)

In [8]:
adata = adata[:,adata.var.highly_variable.values]

In [9]:
# Another option is to save genes, reload data and then filter
adata.X = (np.exp(adata.X) -1).round(0)

In [10]:
X = adata.X

In [11]:
spots = adata.obs_names
genes = adata.var_names
n_spots = len(adata.obs_names)
n_genes = len(adata.var_names)

## Assign random factors

In [12]:
def assign_random(adata, K):
    umi_factor_list = []
    all_n_umis = adata.X.sum(axis=1)
    for n_UMIs in all_n_umis:
        factors = np.random.randint(low = 0,
                                    high = K,
                                    size = int(n_UMIs))
        umi_factor_list.append(factors)
    return umi_factor_list

In [13]:
umi_factors = assign_random(adata, 3)

## Get IDs and count matrices

In [14]:
def get_ids_dt_wt(adata, umi_factors, K):
    n_spots, n_genes = adata.X.shape
    X = adata.X
    ids = []
    dt = np.zeros((n_spots, K))
    wt = np.zeros((K, n_genes))
    for spot in range(n_spots):
        ids_spot = []
        spot_list = umi_factors[spot].tolist()
        start = 0
        end = 0
        for gene in range(n_genes):
            n_umis = int(X[spot, gene])
            ids_spot += [gene] * n_umis
            end += n_umis
            for factor in range(K):
                wt[factor, gene] += spot_list[start: end].count(factor)
            start = end
        ids.append(ids_spot)
        for factor in range(K):
            dt[spot, factor] = spot_list.count(factor)
    return ids, dt, wt

In [15]:
ids, dt, wt = get_ids_dt_wt(adata, umi_factors, 3)

In [16]:
assert(np.all(np.sum(dt,axis=1) == np.sum(X,axis=1))), "total UMI's in spot and dt rowsums must be equal"

## Functions for calculating theta and phi

In [17]:
def get_theta(dt):
    n_spots, K = dt.shape
    theta = np.zeros((n_spots, K))
    for spot in range(n_spots):
        for factor in range(K):
            theta[spot, factor] = dt[spot, factor]/np.sum(dt, axis=1)[spot]
    return theta

In [18]:
theta = get_theta(dt)

In [19]:
def get_phi(wt): # I don't use this...
    phi = wt/wt.sum(axis=1, keepdims=True)
    return phi

In [20]:
phi = get_phi(wt)

## Get neighbours and graph edges

In [21]:
def findKNN(adata, n_neighbours):
    kd = KDTree(adata.obsm["spatial"])
    dist,indx = kd.query(adata.obsm["spatial"], k = n_neighbours + 1)
    return dist, indx

In [22]:
dist, indx = findKNN(adata, 6)

In [23]:
u,c = np.unique(indx[:,-1],return_counts = True) # Can't remember why we did this...

In [24]:
def remove_false_neighbours(dist, indx, eps = 300):
    dist_sel = []
    indx_sel = []
    for i in range(len(dist)):
        dist_sel.append([])
        indx_sel.append([])
        for j in range(len(dist[i])):
            if dist[i][j] < eps:
                dist_sel[i].append(dist[i][j])
                indx_sel[i].append(indx[i][j])
        dist_sel[i] = np.array(dist_sel[i])
        indx_sel[i] = np.array(indx_sel[i])
    return np.array(dist_sel, dtype=object), np.array(indx_sel, dtype=object)

In [25]:
dist_sel, indx_sel = remove_false_neighbours(dist, indx)

In [26]:
def get_E(indx_sel):
    edges = 0
    for i in indx_sel:
        edges += len(i) - 1
    return edges

In [27]:
E = get_E(indx_sel)

## Get first lambda and l_dd

In [28]:
@njit(parallel=False)
def Bhatt_dist(p, q, X):
    BC = 0
    for x in range(X):
        BC += math.sqrt(p[x]*q[x])
    DB = - math.log(BC)
    return DB

In [29]:
lambda0 = np.random.gamma(0.01, 0.01, 1)

In [30]:
lambda0

array([4.92482907e-17])

In [31]:
def first_edge_influence(lambda0, theta, indx_sel, K):
    edge_influence = []
    n_spots = len(indx_sel)
    X = K
    for spot in range(n_spots):
        p = theta[0]
        print(p)
        influences = []
        neighbours = indx_sel[spot][1:]
        for neighbour in neighbours:
            q = theta[neighbour]
            print(q)
            print(Bhatt_dist(p, q, X))
            influences.append(np.random.exponential(lambda0 + Bhatt_dist(p, q, X)))
        edge_influence.append(influences)
    return np.array(edge_influence, dtype=object)

In [32]:
edge_influence = first_edge_influence(lambda0, theta, indx_sel, 3)

[0.34823848 0.33130081 0.3204607 ]
[0.3283458  0.35577722 0.31587697]
0.00037263054073066444
[0.34073014 0.30422334 0.35504653]
0.0007522773990893102
[0.34489938 0.33310201 0.32199861]
6.162599859163077e-06
[0.40853659 0.32926829 0.26219512]
0.0026684361306585887
[0.32150033 0.34829203 0.33020764]
0.00040978321136136606
[0.32842849 0.33725721 0.3343143 ]
0.00023159970334198814
[0.34823848 0.33130081 0.3204607 ]
[0.34760766 0.32464115 0.3277512 ]
3.7547550770668607e-05
[0.33518115 0.34448624 0.32033261]
0.00012671010460679267
[0.34428836 0.32971111 0.32600053]
1.8457352460779942e-05
[0.32919255 0.32897072 0.34183673]
0.0003085244922675066
[0.33175 0.341   0.32725]
0.00015275611090169097
[0.33051742 0.33072862 0.33875396]
0.00024277306064046298
[0.34823848 0.33130081 0.3204607 ]
[0.35625    0.34791667 0.29583333]
0.00037060927965110716
[0.34734513 0.30973451 0.34292035]
0.000371950519826936
[0.35057471 0.3591954  0.29022989]
0.0006583610401921495
[0.32097004 0.34522111 0.33380884]
0.0004

[0.35135135 0.35521236 0.29343629]
0.0005094231225320776
[0.34016393 0.31352459 0.34631148]
0.00039694472113486936
[0.3591954  0.32471264 0.31609195]
6.646781240267153e-05
[0.34169279 0.28526646 0.37304075]
0.0018758109056113178
[0.34823848 0.33130081 0.3204607 ]
[0.33470226 0.33880903 0.32648871]
0.00010215943134012255
[0.32638165 0.33159541 0.34202294]
0.00035267092261421584
[0.33521127 0.30046948 0.36431925]
0.001142094115679742
[0.31343284 0.33378562 0.35278155]
0.0008488516210404993
[0.33478261 0.32753623 0.33768116]
0.00018433680850651015
[0.33933162 0.32990574 0.33076264]
7.032972408193213e-05
[0.34823848 0.33130081 0.3204607 ]
[0.32739761 0.3253625  0.34723989]
0.0004428912033790663
[0.33506261 0.33255814 0.33237925]
0.00011852688757852177
[0.33686195 0.33976218 0.32337587]
7.720794332233505e-05
[0.33468651 0.32972485 0.33558863]
0.00015541018310254043
[0.33148597 0.32906131 0.33945272]
0.00024183811397116082
[0.34241998 0.32465705 0.33292297]
8.851164533960334e-05
[0.34823848 

[0.34433541 0.32292596 0.33273863]
9.000702833929025e-05
[0.33733055 0.34775808 0.31491137]
0.00015524718315026304
[0.35055592 0.32243296 0.32701112]
4.856476000786517e-05
[0.35373537 0.33123312 0.3150315 ]
2.2359199230864818e-05
[0.34823848 0.33130081 0.3204607 ]
[0.33173077 0.33942308 0.32884615]
0.000151881307724026
[0.32538194 0.33878317 0.3358349 ]
0.00030492653381838307
[0.33419689 0.33231276 0.33349034]
0.00013754047270098294
[0.33774834 0.33333333 0.32891832]
6.920207387178634e-05
[0.34484795 0.32388544 0.33126661]
6.992605494614316e-05
[0.32883817 0.33195021 0.33921162]
0.0002724677563519282
[0.34823848 0.33130081 0.3204607 ]
[0.33979136 0.32518629 0.33502235]
0.0001210554612834483
[0.32691763 0.34673082 0.32635154]
0.0002696116175020467
[0.33913841 0.3238619  0.33699969]
0.00015527823479949342
[0.33322991 0.34439963 0.32237046]
0.00014756388224743526
[0.33988764 0.32945425 0.33065811]
6.655765721977446e-05
[0.33618402 0.33588912 0.32792687]
8.24676301467323e-05
[0.34823848 0.

0.0001598747561184952
[0.33141962 0.32620042 0.34237996]
0.00029526068532326427
[0.34065073 0.32418659 0.33516268]
0.00012263696579508526
[0.34764278 0.32234573 0.3300115 ]
6.586284990022973e-05
[0.32349323 0.34112341 0.33538335]
0.00034879895296827985
[0.34823848 0.33130081 0.3204607 ]
[0.34354575 0.32495915 0.3314951 ]
6.997440949894889e-05
[0.32837029 0.32626639 0.34536333]
0.00038852596559091134
[0.32588774 0.33906071 0.33505155]
0.0002890136808659653
[0.33817062 0.34256816 0.31926121]
8.458712801059883e-05
[0.33526358 0.32408147 0.34065495]
0.00023573852436340102
[0.33609959 0.32949132 0.3344091 ]
0.00012936363989332335
[0.34823848 0.33130081 0.3204607 ]
[0.31765613 0.31842714 0.36391673]
0.0011062399423137738
[0.33142857 0.33274725 0.33582418]
0.0001946866909239891
[0.32339657 0.35140018 0.32520325]
0.0003865387657409468
[0.33460699 0.31495633 0.35043668]
0.0005065263125945071
[0.32681683 0.3319167  0.34126647]
0.0003337678676616677
[0.31974374 0.34420501 0.33605125]
0.0004583303

0.000735847077623998
[0.3015873  0.35064935 0.34776335]
0.0012554161553599182
[0.34823848 0.33130081 0.3204607 ]
[0.34125677 0.33490233 0.3238409 ]
2.6975676781010813e-05
[0.33517459 0.34069836 0.32412705]
0.00010051199406088699
[0.33301916 0.33239083 0.33459001]
0.00016167162814469864
[0.32471314 0.33567392 0.33961295]
0.0003518517748147767
[0.36134088 0.31649978 0.32215934]
0.00014617734042079395
[0.32380074 0.32687577 0.34932349]
0.0005409064729018347
[0.34823848 0.33130081 0.3204607 ]
[0.34927697 0.32035595 0.33036707]
8.404810987231157e-05
[0.32201987 0.34354305 0.33443709]
0.00038667521228041466
[0.3447205  0.30952381 0.34575569]
0.0004298090433807372
[0.31058824 0.36411765 0.32529412]
0.0009351980261655794
[0.33892617 0.31431767 0.34675615]
0.00040251852695361815
[0.34823848 0.33130081 0.3204607 ]
[0.3324937  0.34256927 0.32493703]
0.00014593664949679106
[0.31862745 0.33088235 0.3504902 ]
0.0006653293056737193
[0.33793103 0.30344828 0.35862069]
0.0008812960876869683
[0.325 0.325

[0.33564314 0.33044608 0.33391078]
0.0001274037265079497
[0.33746224 0.33323263 0.32930514]
7.384666676538529e-05
[0.33071749 0.3348281  0.33445441]
0.00019250269528720655
[0.33014354 0.33040936 0.3394471 ]
0.0002576135998058607
[0.34585799 0.33106509 0.32307692]
4.721028291805043e-06
[0.33737646 0.33333333 0.32929021]
7.457799638610068e-05
[0.34823848 0.33130081 0.3204607 ]
[0.33209762 0.32808156 0.33982082]
0.00024165182546098974
[0.34402052 0.33504328 0.3209362 ]
1.1768175363174518e-05
[0.33937722 0.32597556 0.33464722]
0.00011615515456046777
[0.33417775 0.32615579 0.33966646]
0.00022224900082021292
[0.32842205 0.34838403 0.32319392]
0.0002554089397990488
[0.33081571 0.33897281 0.33021148]
0.00017027555984117185
[0.34823848 0.33130081 0.3204607 ]
[0.35885167 0.29784689 0.34330144]
0.0006816405540526175
[0.32796209 0.33791469 0.33412322]
0.00023970447465978856
[0.3289689  0.33169667 0.33933442]
0.0002722006310961707
[0.31987768 0.3412844  0.33883792]
0.0004663519629990443
[0.32673267

8.339029465883359e-05
[0.33321517 0.33179724 0.33498759]
0.00016341799345588048
[0.32016008 0.34267134 0.33716858]
0.00044921314327237596
[0.34823848 0.33130081 0.3204607 ]
[0.32590651 0.33813893 0.33595457]
0.00029394200473619456
[0.32745314 0.32194046 0.35060639]
0.0005322822655322063
[0.3260468  0.34328818 0.33066502]
0.0002759176868612657
[0.34901532 0.32549234 0.32549234]
2.285756431540078e-05
[0.33166009 0.3345285  0.3338114 ]
0.000173115721866354
[0.32600061 0.34249924 0.33150015]
0.0002767188467832656
[0.34823848 0.33130081 0.3204607 ]
[0.32651715 0.34212841 0.33135444]
0.00026393505299156006
[0.32392273 0.32927192 0.34680535]
0.0004817870813938506
[0.32625658 0.33006714 0.34367628]
0.00038273760913532385
[0.32380074 0.32687577 0.34932349]
0.0005409064729018347
[0.34125677 0.33490233 0.3238409 ]
2.6975676781010813e-05
[0.31936163 0.3425114  0.33812697]
0.00047765113207334363
[0.34823848 0.33130081 0.3204607 ]
[0.35343788 0.32689988 0.31966224]
1.7237683511216885e-05
[0.34135214

[0.3414505  0.32662785 0.33192165]
7.534270727308146e-05
[0.34823848 0.33130081 0.3204607 ]
[0.33121827 0.33883249 0.32994924]
0.00016238855029069863
[0.33030303 0.32272727 0.3469697 ]
0.0004100471551437837
[0.25531915 0.36170213 0.38297872]
0.0053373615357844555
[0.33184391 0.32767352 0.34048257]
0.00025550834408893345
[0.33474012 0.33984896 0.32541093]
0.00010341205586987018
[0.32907472 0.33836624 0.33255904]
0.00021028043016258605
[0.34823848 0.33130081 0.3204607 ]
[0.31843575 0.36312849 0.31843575]
0.0006999682637780913
[0.32300358 0.32061979 0.35637664]
0.0007580956804916176
[0.32672234 0.31941545 0.35386221]
0.0006398719484184845
[0.36279926 0.31860037 0.31860037]
0.00013797022244637296
[0.332 0.366 0.302]
0.000665995140747433
[0.32432432 0.34511435 0.33056133]
0.00032240819132918827
[0.34823848 0.33130081 0.3204607 ]
[0.33444723 0.3219159  0.34363687]
0.00030568155852763547
[0.33054483 0.33483483 0.33462033]
0.0001965543441631674
[0.32094505 0.33607645 0.3429785 ]
0.000478196521

6.0322280488643945e-05
[0.3285991  0.33634603 0.33505487]
0.00023329464656008262
[0.35029191 0.33861551 0.31109258]
5.622062078444166e-05
[0.32336018 0.34177215 0.33486766]
0.0003504555677153254
[0.34823848 0.33130081 0.3204607 ]
[0.34201508 0.33767421 0.32031072]
2.9217550915583537e-05
[0.33003893 0.33722671 0.33273435]
0.00019291651178079174
[0.33264195 0.33082707 0.33653098]
0.0001877153077204731
[0.3436409  0.31072319 0.34563591]
0.0004106087932195661
[0.34302326 0.32711138 0.32986536]
5.050533262843674e-05
[0.33247349 0.33906563 0.32846088]
0.00013844336899405762
[0.34823848 0.33130081 0.3204607 ]
[0.33042328 0.34074074 0.32883598]
0.0001771110003558253
[0.33860938 0.32249859 0.33889203]
0.00019222713432915007
[0.31859322 0.33669511 0.34471166]
0.0005618048581878829
[0.33824251 0.32547865 0.33627884]
0.0001445660431983667
[0.32542655 0.32667499 0.34789846]
0.00048313460900744026
[0.33640303 0.32502709 0.33856988]
0.00019059154287062277
[0.34823848 0.33130081 0.3204607 ]
[0.3463789

[0.34659091 0.31420455 0.33920455]
0.00024740074246845515
[0.33744856 0.33392122 0.32863022]
7.073961425097898e-05
[0.34550989 0.3173516  0.33713851]
0.00018346382276159312
[0.34731935 0.31876457 0.33391608]
0.00012993190838937158
[0.34823848 0.33130081 0.3204607 ]
[0.34823848 0.33130081 0.3204607 ]
-0.0
[0.32842849 0.33725721 0.3343143 ]
0.00023159970334198814
[0.32751678 0.33825503 0.33422819]
0.00024936861505398276
[0.34829443 0.31238779 0.33931777]
0.0002737609582859631
[0.34489938 0.33310201 0.32199861]
6.162599859163077e-06
[0.33450882 0.31536524 0.35012594]
0.0004955838767517104
[0.34823848 0.33130081 0.3204607 ]
[0.33898305 0.33198231 0.32903464]
5.963821322569621e-05
[0.32644628 0.34504132 0.3285124 ]
0.00027082356660466564
[0.34051962 0.31398563 0.34549475]
0.00037322134137586624
[0.32542694 0.34313725 0.3314358 ]
0.000291340956802328
[0.33671171 0.3170045  0.34628378]
0.0003775205120512523
[0.33284529 0.33333333 0.33382138]
0.00015676732127451357
[0.34823848 0.33130081 0.320

0.0005497710983361516
[0.32856213 0.32856213 0.34287573]
0.0003353512580293935
[0.32953865 0.34152187 0.32893948]
0.00019552220252740354
[0.33560014 0.33151989 0.33287997]
0.00011744820440382193
[0.31446541 0.33153639 0.3539982 ]
0.0008481220607323754
[0.31372549 0.34117647 0.34509804]
0.0007147553635285701
[0.34823848 0.33130081 0.3204607 ]
[0.34501845 0.33948339 0.31549815]
3.837580492528971e-05
[0.30397237 0.33333333 0.3626943 ]
0.0014078662217357396
[0.32079646 0.3329646  0.34623894]
0.0005319762010944361
[0.33787466 0.32207084 0.3400545 ]
0.00021710284409514672
[0.41371681 0.31637168 0.2699115 ]
0.0025827238477921554
[0.36166667 0.30833333 0.33      ]
0.0003047696274971124
[0.34823848 0.33130081 0.3204607 ]
[0.32686254 0.34365163 0.32948583]
0.00025712196129468103
[0.32423756 0.33386838 0.34189406]
0.0003902102406683606
[0.32907197 0.33380682 0.33712121]
0.00024355539955409327
[0.33216169 0.33787346 0.32996485]
0.00014585183912072897
[0.32824712 0.3461109  0.32564198]
0.0002391007

0.0004900209267510604
[0.32930989 0.33167148 0.33901863]
0.0002628957308652853
[0.331879   0.33595113 0.33216987]
0.00015903095860437473
[0.34823848 0.33130081 0.3204607 ]
[0.31446541 0.33153639 0.3539982 ]
0.0008481220607323754
[0.31147541 0.33558341 0.35294118]
0.0009117411354530198
[0.33240223 0.33798883 0.32960894]
0.0001410315612742185
[0.33143322 0.34446254 0.32410423]
0.00017315293074173015
[0.3172988  0.34320074 0.33950046]
0.0005497710983361516
[0.3182243  0.34205607 0.33971963]
0.0005216664619196158
[0.34823848 0.33130081 0.3204607 ]
[0.33716858 0.30415208 0.35867934]
0.0008733007067460717
[0.34923339 0.33219761 0.31856899]
2.0578367225070475e-06
[0.33815314 0.33453828 0.32730858]
5.9084329394545737e-05
[0.33520337 0.3345021  0.33029453]
0.00010316581376404892
[0.34823848 0.33130081 0.3204607 ]
[0.340625   0.31041667 0.34895833]
0.000494547043611854
[0.31168831 0.34487734 0.34343434]
0.0007737342415219036
[0.34021739 0.33804348 0.32173913]
4.098204546449656e-05
[0.34266667 0.

[0.33162584 0.3363029  0.33207127]
0.00016253270070478863
[0.34823848 0.33130081 0.3204607 ]
[0.33226103 0.33455882 0.33318015]
0.00015967865447587135
[0.32709308 0.32969319 0.34321373]
0.0003616752495520321
[0.35737705 0.32177986 0.32084309]
6.43513712881085e-05
[0.32918611 0.33022291 0.34059098]
0.0002877544507191497
[0.33686731 0.3255814  0.3375513 ]
0.000170644048338918
[0.34966035 0.31390776 0.33643189]
0.00021507808568998628
[0.34823848 0.33130081 0.3204607 ]
[0.34427452 0.32189482 0.33383066]
0.00010784997923678793
[0.33974976 0.32820019 0.33205005]
8.129723707113238e-05
[0.33139136 0.32488005 0.34372858]
0.00032402276569142317
[0.33452915 0.33423019 0.33124066]
0.00011663638819862204
[0.32258065 0.33870968 0.33870968]
0.0003923212398393777
[0.31801418 0.3387234  0.34326241]
0.0005595608418221609
[0.34823848 0.33130081 0.3204607 ]
[0.32398397 0.33772181 0.33829422]
0.00035504065169127683
[0.34301977 0.32444578 0.33253445]
8.358422169652872e-05
[0.34273404 0.33529181 0.32197415]


[0.31677019 0.36645963 0.31677019]
0.0008213380785996065
[0.37128713 0.34653465 0.28217822]
0.0008792027598562695
[0.37931034 0.26724138 0.35344828]
0.0024577835892845797
[0.33206107 0.32442748 0.34351145]
0.00031436935370170036
[0.34823848 0.33130081 0.3204607 ]
[0.32813403 0.3113807  0.36048527]
0.0008928706152050356
[0.3111413  0.36141304 0.32744565]
0.0008687946108296608
[0.33161807 0.35048599 0.31789594]
0.00023919187584384456
[0.31327801 0.34024896 0.34647303]
0.0007460519055548368
[0.32793959 0.3236246  0.34843581]
0.00046760777902577334
[0.33086603 0.3434493  0.32568468]
0.00017638169867254905
[0.34823848 0.33130081 0.3204607 ]
[0.32876712 0.35616438 0.31506849]
0.00037642555091756537
[0.34843206 0.32055749 0.33101045]
8.699833945834194e-05
[0.36285714 0.34       0.29714286]
0.00032354833052280536
[0.34591195 0.35849057 0.29559748]
0.000521089539038546
[0.3374613 0.3250774 0.3374613]
0.0001669564986023886
[0.27848101 0.34599156 0.37552743]
0.003122625385603482
[0.34823848 0.331

[0.34823848 0.33130081 0.3204607 ]
[0.33489461 0.34689696 0.31820843]
0.0001568426033522051
[0.33102362 0.34204724 0.32692913]
0.0001681407307201783
[0.32622061 0.33743219 0.3363472 ]
0.0002899162604048282
[0.32726826 0.34546349 0.32726826]
0.0002548109697581242
[0.32916667 0.34134615 0.32948718]
0.00020313319552506823
[0.34249184 0.3163765  0.34113166]
0.00025947404211591713
[0.34823848 0.33130081 0.3204607 ]
[0.33247349 0.33906563 0.32846088]
0.00013844336899405762
[0.32337388 0.34320465 0.33342147]
0.0003470306346147202
[0.32635135 0.33885135 0.3347973 ]
0.00027731424609532036
[0.33769124 0.34130737 0.32100139]
7.788404008074466e-05
[0.32699463 0.34415048 0.3288549 ]
0.0002554135589165937
[0.34201508 0.33767421 0.32031072]
2.9217550915583537e-05
[0.34823848 0.33130081 0.3204607 ]
[0.3274434  0.33489785 0.33765875]
0.00027730590190818875
[0.32448454 0.32783505 0.34768041]
0.0004917750920085596
[0.34137594 0.33192044 0.32670362]
3.227446840702889e-05
[0.3372093  0.32468694 0.33810376]

[0.31909983 0.34622043 0.33467975]
0.00047764995963953246
[0.32934609 0.33133971 0.33931419]
0.00026646605734016715
[0.32745007 0.32977241 0.34277752]
0.0003486611919573382
[0.34823848 0.33130081 0.3204607 ]
[0.34241908 0.33276547 0.32481545]
2.0413681938403427e-05
[0.32860262 0.34061135 0.33078603]
0.00021565128530971116
[0.32478336 0.32894281 0.34627383]
0.0004565643879195917
[0.33248408 0.34840764 0.31910828]
0.0001995534689129196
[0.33206107 0.32951654 0.33842239]
0.00021985155942452091
[0.3459168  0.32896764 0.32511556]
1.2393489994901212e-05
[0.34823848 0.33130081 0.3204607 ]
[0.33002646 0.34490741 0.32506614]
0.00019896308284176082
[0.34896142 0.33531157 0.315727  ]
1.502606193316075e-05
[0.33421751 0.34261715 0.32316534]
0.0001223802236818353
[0.33062645 0.32598608 0.34338747]
0.0003230536031247297
[0.32530554 0.34507549 0.32961898]
0.00029770299878724237
[0.34311111 0.32844444 0.32844444]
3.715695994913659e-05
[0.34823848 0.33130081 0.3204607 ]
[0.34435717 0.32823481 0.3274080

0.00024642369196629514
[0.32201646 0.35185185 0.32613169]
0.00042368249729108525
[0.36390244 0.30634146 0.3297561 ]
0.00036377484479690726
[0.33778148 0.34487073 0.31734779]
0.00011174545095517868
[0.331076   0.34462002 0.32430399]
0.000179781770936663
[0.34823848 0.33130081 0.3204607 ]
[0.33264569 0.35482207 0.31253223]
0.00031580587326922934
[0.32934609 0.33133971 0.33931419]
0.00026646605734016715
[0.33009259 0.33888889 0.33101852]
0.00018564998114001962
[0.32993401 0.34553089 0.32453509]
0.0002047948682340391
[0.31884058 0.34903382 0.3321256 ]
0.0004918709277485641
[0.33029979 0.33190578 0.33779443]
0.00023287968582864064
[0.34823848 0.33130081 0.3204607 ]
[0.33822297 0.3394803  0.32229673]
6.278285828886076e-05
[0.33559499 0.33402923 0.33037578]
9.901359940549156e-05
[0.33792566 0.33350663 0.32856772]
6.590083325624508e-05
[0.34421365 0.32838773 0.32739862]
2.7639900423838857e-05
[0.34435717 0.32823481 0.32740802]
2.7626562201555386e-05
[0.34769231 0.33230769 0.32      ]
5.7194074

[0.34751773 0.29078014 0.36170213]
0.0012854680176701448
[0.34768212 0.35099338 0.3013245 ]
0.00028954567214253303
[0.31861804 0.34357006 0.3378119 ]
0.0004993345545174124
[0.27848101 0.34599156 0.37552743]
0.003122625385603482
[0.35416667 0.34166667 0.30416667]
0.00015871995102961415
[0.34823848 0.33130081 0.3204607 ]
[0.33046927 0.33377396 0.33575677]
0.00020779231027693708
[0.33722912 0.32675919 0.33601169]
0.0001441635702786139
[0.32474891 0.34148854 0.33376255]
0.00031126807903346224
[0.33252954 0.33084157 0.33662889]
0.00019020466138037172
[0.33408255 0.3363302  0.32958725]
0.00011494410679776055
[0.32993103 0.32358621 0.34648276]
0.0004002987181656366
[0.34823848 0.33130081 0.3204607 ]
[0.33437589 0.32613022 0.33949389]
0.00021783675227842793
[0.32907472 0.33836624 0.33255904]
0.00021028043016258605
[0.34629898 0.32249637 0.33120464]
7.52862904730525e-05
[0.33121827 0.33883249 0.32994924]
0.00016238855029069863
[0.34064885 0.31679389 0.34255725]
0.00028629177726839465
[0.3341577

[0.33482143 0.33392857 0.33125   ]
0.00011315233001051326
[0.3359616  0.33356188 0.33047652]
9.553360017835135e-05
[0.32858215 0.33383346 0.3375844 ]
0.000256606897096891
[0.33710247 0.33710247 0.32579505]
6.88398152374595e-05
[0.31425016 0.34847542 0.33727442]
0.0006524012908620357
[0.34823848 0.33130081 0.3204607 ]
[0.3414264  0.30728376 0.35128983]
0.0005968012202534755
[0.33580858 0.3349835  0.32920792]
9.10086100718945e-05
[0.33452381 0.31547619 0.35      ]
0.0004913288740793567
[0.31981982 0.33742834 0.34275184]
0.0005038863264207131
[0.34018499 0.33299075 0.32682425]
4.027035484734285e-05
[0.36182903 0.32803181 0.31013917]
0.00011133227082202612
[0.34823848 0.33130081 0.3204607 ]
[0.33117304 0.34089436 0.3279326 ]
0.00016295067716640992
[0.3369391  0.32612179 0.3369391 ]
0.0001600790982325031
[0.32326174 0.32435384 0.35238442]
0.0006298113629715151
[0.31716418 0.33665008 0.34618574]
0.0006221605373808851
[0.32891623 0.33743493 0.33364884]
0.0002184377986811571
[0.33195799 0.3304

0.00016838992144973232
[0.34746017 0.33453562 0.31800421]
6.509458601571695e-06
[0.32801334 0.32491663 0.34707003]
0.0004321599185659686
[0.33634992 0.32428356 0.33936652]
0.0002058709151902282
[0.34823848 0.33130081 0.3204607 ]
[0.35972851 0.32352941 0.31674208]
7.510910419602295e-05
[0.34570312 0.33789062 0.31640625]
2.4992635977477194e-05
[0.35501859 0.34572491 0.29925651]
0.0002746486764499654
[0.35609756 0.31463415 0.32926829]
0.0001593142259317288
[0.32113821 0.30894309 0.3699187 ]
0.0013574917395795007
[0.33139535 0.33139535 0.3372093 ]
0.0002110456960439131
[0.34823848 0.33130081 0.3204607 ]
[0.33209647 0.33364255 0.33426098]
0.00017056720190867527
[0.3249941  0.33537881 0.33962709]
0.00034615162921701877
[0.33175 0.341   0.32725]
0.00015275611090169097
[0.33468913 0.33149332 0.33381755]
0.0001354106773882849
[0.33061924 0.33661881 0.33276195]
0.00018286341389246377
[0.32919255 0.32897072 0.34183673]
0.0003085244922675066
[0.34823848 0.33130081 0.3204607 ]
[0.32858215 0.3338334

[0.33108677 0.34625105 0.32266217]
0.00019266165294730162
[0.34823848 0.33130081 0.3204607 ]
[0.32805817 0.3421728  0.32976903]
0.00022779657475610406
[0.32588774 0.33906071 0.33505155]
0.0002890136808659653
[0.32594477 0.34229651 0.33175872]
0.00027819669986385435
[0.33045812 0.33294997 0.33659191]
0.00021654236272644162
[0.32984127 0.33904762 0.33111111]
0.00019073347140228646
[0.34354575 0.32495915 0.3314951 ]
6.997440949894889e-05
[0.34823848 0.33130081 0.3204607 ]
[0.33513514 0.31351351 0.35135135]
0.0005409385078202434
[0.29126214 0.34951456 0.3592233 ]
0.0019484534271409578
[0.29829545 0.37215909 0.32954545]
0.0015927296316731894
[0.36594203 0.32246377 0.3115942 ]
0.00017070382604659955
[0.33956386 0.29906542 0.36137072]
0.0010544931086242002
[0.33245033 0.31655629 0.35099338]
0.0005228798397149401
[0.34823848 0.33130081 0.3204607 ]
[0.32870772 0.34865568 0.3226366 ]
0.0002535311300232159
[0.32326284 0.33232628 0.34441088]
0.0004485662671784943
[0.31707317 0.33972125 0.34320557]

[0.32795699 0.34715822 0.32488479]
0.00025239694738790993
[0.34814143 0.34451496 0.30734361]
0.00013313542049785858
[0.32875895 0.32756563 0.34367542]
0.0003484348685057543
[0.32632399 0.33722741 0.3364486 ]
0.0002885007831225728
[0.31844548 0.34860789 0.33294664]
0.0005029523564957757
[0.34823848 0.33130081 0.3204607 ]
[0.30971375 0.33740028 0.35288597]
0.0009693819674593913
[0.34412266 0.32027257 0.33560477]
0.00014019962201564703
[0.33459357 0.33648393 0.3289225 ]
0.00010580241922891366
[0.34471438 0.29612607 0.35915955]
0.0010497536775484668
[0.34476067 0.32276843 0.33247089]
8.742901482812007e-05
[0.3302583  0.33948339 0.3302583 ]
0.0001809925381075799
[0.34823848 0.33130081 0.3204607 ]
[0.34819533 0.34243251 0.30937216]
9.479770048433332e-05
[0.33141962 0.32620042 0.34237996]
0.00029526068532326427
[0.31650958 0.34417756 0.33931286]
0.0005750618822012797
[0.329339   0.32740626 0.34325474]
0.00033338931991016207
[0.32890792 0.33404711 0.33704497]
0.00024544280589792507
[0.35090679

[0.31585082 0.34662005 0.33752914]
0.0005925608643974734
[0.3375     0.32972973 0.33277027]
0.00010097752293485994
[0.34604475 0.33217775 0.3217775 ]
2.697622057668776e-06
[0.33405106 0.33681944 0.3291295 ]
0.00011408588979903651
[0.33164717 0.34113184 0.32722099]
0.00015482230718895436
[0.32806777 0.33104396 0.34088828]
0.0003082809360760741
[0.34823848 0.33130081 0.3204607 ]
[0.33009566 0.33245033 0.33745401]
0.0002316073755161134
[0.32900729 0.33606557 0.33492714]
0.00022492023039518316
[0.34823848 0.33130081 0.3204607 ]
[0.35502959 0.31952663 0.32544379]
7.926556923943335e-05
[0.33140376 0.36034732 0.30824891]
0.00046877395488205946
[0.32919847 0.33206107 0.33874046]
0.00026081214106412037
[0.33333333 0.34821429 0.31845238]
0.00018835760135828036
[0.30179028 0.35294118 0.34526854]
0.001233906498393274
[0.33139535 0.33139535 0.3372093 ]
0.0002110456960439131
[0.34823848 0.33130081 0.3204607 ]
[0.33920352 0.33520112 0.32559536]
4.55970719233093e-05
[0.32602574 0.33829445 0.33567981]


[0.34104046 0.3492981  0.30966144]
0.0001840810055854719
[0.33079158 0.33115468 0.33805374]
0.00022964849282640818
[0.32969961 0.33793605 0.33236434]
0.00019749823699796964
[0.32719234 0.3596168  0.31319086]
0.00047519392309328215
[0.34823848 0.33130081 0.3204607 ]
[0.34367201 0.33832442 0.31800357]
2.831693815083078e-05
[0.34444219 0.33123349 0.32432432]
1.0991146909029306e-05
[0.3339196  0.33090452 0.33517588]
0.00015779801410563139
[0.32286024 0.34561213 0.33152763]
0.0003626945532291961
[0.32803842 0.34004433 0.33191725]
0.00022967297673659646
[0.33525346 0.32488479 0.33986175]
0.00021992341981292893
[0.34823848 0.33130081 0.3204607 ]
[0.34787291 0.32040926 0.33171782]
9.414155007405754e-05
[0.31766452 0.35378525 0.32855022]
0.0005610246759944431
[0.32499007 0.32936035 0.34564958]
0.0004405032776678656
[0.35204241 0.31774244 0.33021515]
0.00011254763495015126
[0.34801197 0.31466439 0.33732364]
0.0002152667223175771
[0.31270903 0.34740803 0.33988294]
0.0007164987197993423
[0.3482384

[0.34074074 0.32063492 0.33862434]
0.0001892102204336034
[0.30673317 0.35860349 0.33466334]
0.001005925205694145
[0.34163037 0.30678283 0.35158681]
0.0006122189181486948
[0.34823848 0.33130081 0.3204607 ]
[0.33915575 0.3216885  0.33915575]
0.00019789216698137393
[0.35687168 0.33181473 0.31131359]
5.963876514137236e-05
[0.34074074 0.32063492 0.33862434]
0.0001892102204336034
[0.36107987 0.31833521 0.32058493]
0.00012283706806093513
[0.34035088 0.3245614  0.33508772]
0.00012151110643949052
[0.3221831  0.35387324 0.32394366]
0.00044401321471481374
[0.34823848 0.33130081 0.3204607 ]
[0.33310742 0.32429685 0.34259573]
0.0002875514678054009
[0.33491686 0.3365004  0.32858274]
0.00010048632861804918
[0.32472178 0.34697933 0.32829889]
0.000319853087990911
[0.34301977 0.32444578 0.33253445]
8.358422169652872e-05
[0.33459945 0.33408149 0.33131906]
0.00011625236123988945
[0.33769814 0.33631978 0.32598208]
6.171881169909022e-05
[0.34823848 0.33130081 0.3204607 ]
[0.33825406 0.33151084 0.3302351 ]
7

3.4664049061188076e-06
[0.34002361 0.3270366  0.33293979]
9.101158849378568e-05
[0.34823848 0.33130081 0.3204607 ]
[0.33997155 0.33854908 0.32147937]
4.4840518756070175e-05
[0.32944345 0.32136445 0.3491921 ]
0.00047659757776036114
[0.32142857 0.32668067 0.35189076]
0.0006442689075003624
[0.31840448 0.34429671 0.33729881]
0.0005043634011950445
[0.34088457 0.33495146 0.32416397]
2.993968790604064e-05
[0.32069672 0.32479508 0.3545082 ]
0.0007296435876174121
[0.34823848 0.33130081 0.3204607 ]
[0.33463833 0.34004474 0.32531693]
0.00010532959867891011
[0.34199497 0.33340319 0.32460184]
2.2428196836601657e-05
[0.3260915  0.33883434 0.33507416]
0.0002845583194849136
[0.32700838 0.33242977 0.34056185]
0.0003202940873167315
[0.33772136 0.32957217 0.33270647]
9.885158231195128e-05
[0.33740953 0.327427   0.33516346]
0.0001309038000331222
[0.34823848 0.33130081 0.3204607 ]
[0.33801437 0.32168517 0.34030046]
0.0002224675095963095
[0.31814672 0.35057915 0.33127413]
0.0005211650804563668
[0.34335686 0

[0.31626898 0.34577007 0.33796095]
0.0005785216871843125
[0.33667522 0.32898111 0.33434367]
0.0001244476034127815
[0.34823848 0.33130081 0.3204607 ]
[0.33139136 0.32488005 0.34372858]
0.00032402276569142317
[0.32838634 0.32650177 0.3451119 ]
0.0003828063595172197
[0.32552693 0.33099141 0.34348165]
0.00039117153731705093
[0.34427452 0.32189482 0.33383066]
0.00010784997923678793
[0.34566787 0.33393502 0.32039711]
4.9900858132003216e-06
[0.32872117 0.33081761 0.34046122]
0.0002921813280895766
[0.34823848 0.33130081 0.3204607 ]
[0.32712082 0.33419023 0.33868895]
0.00029434671850233886
[0.34185304 0.35782748 0.30031949]
0.0004336468072463982
[0.35264901 0.32284768 0.32450331]
4.058398312579083e-05
[0.35928144 0.34431138 0.29640719]
0.00034036225951637544
[0.33702532 0.3164557  0.34651899]
0.0003856292609045031
[0.34064969 0.35206321 0.30728709]
0.00024779273635893573
[0.34823848 0.33130081 0.3204607 ]
[0.3342723  0.32910798 0.33661972]
0.00017265118388937794
[0.346 0.316 0.338]
0.0002090770

[0.35324232 0.33788396 0.30887372]
7.845544927626492e-05
[0.33432709 0.32793867 0.33773424]
0.00018854443422758885
[0.34050881 0.3334638  0.3260274 ]
3.5431386480800305e-05
[0.32987805 0.35426829 0.31585366]
0.00032510911777061045
[0.31674959 0.35157546 0.33167496]
0.0005718790329940509
[0.34056122 0.33886054 0.32057823]
4.271935161432788e-05
[0.34823848 0.33130081 0.3204607 ]
[0.34463277 0.36440678 0.29096045]
0.0007550889934470335
[0.33449477 0.33449477 0.33101045]
0.00011572366251432654
[0.3412527  0.31317495 0.34557235]
0.0003820229062385252
[0.30519481 0.33333333 0.36147186]
0.0013292199721616556
[0.34844869 0.32696897 0.32458234]
1.3726673681650079e-05
[0.36565978 0.31319555 0.32114467]
0.00023368747735399905
[0.34823848 0.33130081 0.3204607 ]
[0.32379395 0.3524121  0.32379395]
0.00038975189677975135
[0.3375481  0.32930181 0.33315008]
0.00010477656508235604
[0.31906977 0.35069767 0.33023256]
0.0004936576706177608
[0.31701445 0.34189406 0.34109149]
0.0005693035885722338
[0.3418745

[0.33982301 0.32430225 0.33587474]
0.00013493199247194097
[0.3426862  0.31565917 0.34165463]
0.00027539382007749064
[0.33552902 0.33539179 0.32907918]
9.393432652685643e-05
[0.33173864 0.33878887 0.32947249]
0.00015227981051518577
[0.34823848 0.33130081 0.3204607 ]
[0.33409402 0.32405294 0.34185304]
0.0002661703682386279
[0.34287043 0.3326355  0.32449407]
1.7400816336816378e-05
[0.31756757 0.33622909 0.34620335]
0.0006112910768543644
[0.32850447 0.34000852 0.331487  ]
0.00021878030328703317
[0.32779661 0.33966102 0.33254237]
0.00023652380644664296
[0.32593493 0.34204926 0.33201581]
0.0002786145114271261
[0.34823848 0.33130081 0.3204607 ]
[0.327654   0.33813893 0.33420708]
0.00024642369196629514
[0.33596392 0.30552424 0.35851184]
0.0008498981141867275
[0.34064786 0.33960293 0.31974922]
4.6793740132460816e-05
[0.34823848 0.33130081 0.3204607 ]
[0.34411277 0.32421227 0.33167496]
7.352717450537253e-05
[0.33556842 0.33587321 0.32855837]
9.179253329740803e-05
[0.32432432 0.33402633 0.3416493

## Functions for Gibbs sampling of variables

In [33]:
def sample_edge_influence(edge_influence, lambda_parameter, theta, indx_sel, K):
    n_spots = len(indx_sel)
    X = K
    for spot in range(n_spots):
        p = theta[spot]
        index = 1
        n_neighbours = len(indx_sel[spot][1:])
        for index in range(n_neighbours):
            neighbour = indx_sel[spot][index+1]
            q = theta[neighbour]
            edge_influence[spot][index] = np.random.exponential(lambda_parameter + Bhatt_dist(p, q, X))

In [34]:
def sample_lambda(E, edge_influence, lambda_a = 0.01, lambda_b = 0.01):
    sum_edge_influences = 0
    for edge in edge_influence:
        sum_edge_influences += sum(edge)
    shape = lambda_a + E
    rate = 1 / (lambda_b + sum_edge_influences)
    lambda_parameter = np.random.gamma(shape, rate, 1)
    return lambda_parameter

In [35]:
lambda_parameter = sample_lambda(E, edge_influence)

In [36]:
def draw_new_factor(umi_factors, ids, spot, w, dt, wt, theta, K, beta = 0.1):
    factor0 = umi_factors[spot][w]
    gene_id = ids[spot][w]
    dt[spot, factor0] -= 1
    wt[factor0, gene_id] -= 1
    left = theta[spot,]
    right = (wt[:,gene_id] + beta) / (wt.sum(axis=0)[gene_id] + K * beta)
    pvals = left*right
    pvals = pvals / pvals.sum()
    factor1 = np.random.choice(K, p = pvals)
    dt[spot, factor1] +=  1
    wt[factor1, gene_id] += 1
    umi_factors[spot][w] = factor1

In [37]:
draw_new_factor(umi_factors, ids, 0, 0, dt, wt, theta, 3)

## Metropolis-Hastings sampling of theta

In [38]:
def metr_hast(theta, indx_sel, edge_influence, lambda_parameter, iterations = 1000):
    
    # Prepare proposal distribution    
    dist_g = lambda x: np.random.dirichlet(x)

    n_spots, X = theta.shape
    
    # Metropolis-Hastings sampling
    for it in range(iterations):
        for spot in range(n_spots):
            log_a_prob0 = 0 # Cannot use from last Gibbs iteration, because there will be new edge_infl and lambdas.
            log_a_prob1 = 0
            p0 = theta[spot]
            p1 = dist_g(np.sum(theta, axis=0)) 
            neighbours = indx_sel[spot][1:]
            index = 0
            for neighbour in neighbours:
                q = theta[neighbour]
                log_edge_potential0 = - Bhatt_dist(p0,q,X) * edge_influence[spot][index] # Double check
                log_edge_potential1 = - Bhatt_dist(p1,q,X) * edge_influence[spot][index]
                log_a_prob0 += log_edge_potential0
                log_a_prob1 += log_edge_potential1
                index += 1
            a_prob = min(1, np.exp(log_a_prob1 - log_a_prob0)) 
#            print(a_prob) # This is really large. Maybe that's normal because everything is better than random?
            if np.random.random() < a_prob:
                p0 = p1
            theta[spot] = p0

In [39]:
%%time
# 10 iterations
metr_hast(theta, indx_sel, edge_influence, lambda_parameter, iterations = 10)

CPU times: user 3.16 s, sys: 20.5 ms, total: 3.18 s
Wall time: 3.19 s


In [40]:
%%time
# 1000 iterations
metr_hast(theta, indx_sel, edge_influence, lambda_parameter)

CPU times: user 5min 12s, sys: 439 ms, total: 5min 12s
Wall time: 5min 12s


## Gibbs sampling

In [41]:
def Gibbs(umi_factors, ids, dt, wt, theta, K, iterations, edge_influence, lambda_parameter, indx_sel, E, beta = 0.1):
    for it in range(iterations):
        for spot in range(len(umi_factors)):
            for w in range(len(umi_factors[spot])):
                draw_new_factor(umi_factors, ids, spot, w, dt, wt, theta, K)
        sample_edge_influence(edge_influence, lambda_parameter, theta, indx_sel, K)
        lambda_parameter = sample_lambda(E, edge_influence, lambda_a = 0.01, lambda_b = 0.01)
        metr_hast(theta, indx_sel, edge_influence, lambda_parameter)

In [42]:
%%time
Gibbs(umi_factors, ids, dt, wt, theta, 3, 1, edge_influence, lambda_parameter, indx_sel, E)

CPU times: user 9min 51s, sys: 957 ms, total: 9min 52s
Wall time: 9min 52s
